# Generated by Django 4.2 on 2025-12-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('qr_number', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='RestrictedFolder',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
