# Generated by Django 4.2 on 2025-12-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_document_remove_trip_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='receipts/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
