# Generated by Django 4.2 on 2025-12-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='qr_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
